version: "3.8"
name: "laravel-app"

services:
  nginx:
    image: "nginx:1.25.3"
    container_name: laravel-app-nginx
    restart: unless-stopped
    depends_on:
      - php
      - postgres
      - adminer
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/app
      - ../data/uploads:/var/www/app/storage/app/public
  php:
    image: laravel-app/php
    build:
      context: src
    container_name: laravel-app-php
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - env/php.env
    volumes:
      - ./src:/var/www/app
      - ../data/uploads:/var/www/app/storage/app/public
  postgres:
    image: postgres:16.0
    container_name: laravel-app-postgres
    restart: unless-stopped
    volumes:
      - ../data/db:/var/lib/postgresql/data
    env_file:
      - .env
  adminer:
    image: adminer:4.8.1-standalone
    container_name: laravel-app-adminer
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: nette
    ports:
      - "${ADMINER_PORT}:8080"
