name: "laravel"

services:
    php:
        build: ./docker/php
        container_name: laravel-php
        restart: unless-stopped
        volumes:
            - .:/var/www
        ports:
            - 5173:5173
        environment:
            ASSET_URL: "${APP_URL}"
    nginx:
        image: nginx:1.27.0-alpine3.19
        container_name: laravel-nginx
        restart: unless-stopped
        ports:
            - "${APP_PORT}:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
    redis:
        image: redis:7.2.5-alpine3.20
        container_name: laravel-redis
        restart: unless-stopped
        command: redis-server --appendonly yes
        volumes:
            - ./docker/redis/data:/data
    postgres:
        image: postgres:16.3-alpine
        container_name: laravel-postgres
        restart: unless-stopped
        volumes:
            - ./docker/db/data:/var/lib/postgresql/data
            - ./docker/db/sql:/docker-entrypoint-initdb.d
        environment:
            POSTGRES_USER: laravel
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
            POSTGRES_DB: laravel
    adminer:
        image: adminer:4.8.1-standalone
        container_name: laravel-adminer
        restart: unless-stopped
        ports:
            - "${ADMINER_PORT}:8080"
        environment:
            ADMINER_DEFAULT_SERVER: postgres
            ADMINER_DESIGN: hydra
