version: '3'

env:
  ENV_FILE: .env
  CONTAINER_NAME: laravel-php

tasks:
  build:
    desc: "Builds application images."
    cmd: docker compose --env-file $ENV_FILE build {{.CLI_ARGS}}
  up:
    desc: "Launches application containers."
    cmd: docker compose --env-file $ENV_FILE up {{.CLI_ARGS}}
  stop:
    desc: "Stops application containers."
    cmd: docker compose --env-file $ENV_FILE stop {{.CLI_ARGS}}
  down:
    desc: "Stops and deletes application containers."
    cmd: docker compose --env-file $ENV_FILE down {{.CLI_ARGS}}
  artisan:
    desc: "Launches Laravel Artisan."
    cmd: docker exec -it $CONTAINER_NAME php artisan {{.CLI_ARGS}}
  composer:
    desc: "Launches Composer."
    cmd: docker exec -it $CONTAINER_NAME composer {{.CLI_ARGS}}
  rector:
    desc: "Formats files using Rector."
    cmd: docker exec -it $CONTAINER_NAME ./vendor/bin/rector
  node:
    desc: "Launches Node.js."
    cmd: docker exec -it $CONTAINER_NAME node {{.CLI_ARGS}}
  npm:
    desc: "Launches NPM."
    cmd: docker exec -it $CONTAINER_NAME npm {{.CLI_ARGS}}
  perms:
    desc: "Sets the necessary permissions on directories."
    cmd: sudo chmod 777 -R storage bootstrap/cache vendor
  format:
    desc: "Formats all code."
    cmds:
      - docker exec -it $CONTAINER_NAME npm run format
      - docker exec -it $CONTAINER_NAME ./vendor/bin/rector
  test:
    desc: "Runs tests."
    cmd: docker exec -it $CONTAINER_NAME php artisan test {{.CLI_ARGS}}
